using System;
using System.Collections.Generic;
using System.IO;

// a) Student class
public class Student
{
    public int Id;
        public string FullName;
            public int Score;

                public Student(int id, string fullName, int score)
                    {
                            Id = id; FullName = fullName; Score = score;
                                }

                                    public string GetGrade()
                                        {
                                                return Score switch
                                                        {
                                                                    >= 80 and <= 100 => "A",
                                                                                >= 70 and <= 79  => "B",
                                                                                            >= 60 and <= 69  => "C",
                                                                                                        >= 50 and <= 59  => "D",
                                                                                                                    < 50             => "F",
                                                                                                                                _                => "F"
                                                                                                                                        };
                                                                                                                                            }
                                                                                                                                            }

                                                                                                                                            // b/c) Custom exceptions
                                                                                                                                            public class InvalidScoreFormatException : Exception
                                                                                                                                            {
                                                                                                                                                public InvalidScoreFormatException(string message) : base(message) { }
                                                                                                                                                }

                                                                                                                                                public class MissingFieldException : Exception
                                                                                                                                                {
                                                                                                                                                    public MissingFieldException(string message) : base(message) { }
                                                                                                                                                    }

                                                                                                                                                    // d) StudentResultProcessor
                                                                                                                                                    public class StudentResultProcessor
                                                                                                                                                    {
                                                                                                                                                        public List<Student> ReadStudentsFromFile(string inputFilePath)
                                                                                                                                                            {
                                                                                                                                                                    var students = new List<Student>();

                                                                                                                                                                            using var sr = new StreamReader(inputFilePath);
                                                                                                                                                                                    string? line;
                                                                                                                                                                                            int lineNum = 0;

                                                                                                                                                                                                    while ((line = sr.ReadLine()) != null)
                                                                                                                                                                                                            {
                                                                                                                                                                                                                        lineNum++;
                                                                                                                                                                                                                                    if (string.IsNullOrWhiteSpace(line)) continue;

                                                                                                                                                                                                                                                var parts = line.Split(',');
                                                                                                                                                                                                                                                            if (parts.Length != 3)
                                                                                                                                                                                                                                                                            throw new MissingFieldException($"Line {lineNum}: Expected 3 fields (Id, FullName, Score) but got {parts.Length}.");

                                                                                                                                                                                                                                                                                        var idStr = parts[0].Trim();
                                                                                                                                                                                                                                                                                                    var name = parts[1].Trim();
                                                                                                                                                                                                                                                                                                                var scoreStr = parts[2].Trim();

                                                                                                                                                                                                                                                                                                                            if (!int.TryParse(idStr, out int id))
                                                                                                                                                                                                                                                                                                                                            throw new FormatException($"Line {lineNum}: Invalid ID format.");

                                                                                                                                                                                                                                                                                                                                                        if (!int.TryParse(scoreStr, out int score))
                                                                                                                                                                                                                                                                                                                                                                        throw new InvalidScoreFormatException($"Line {lineNum}: Score '{scoreStr}' is not a valid integer.");

                                                                                                                                                                                                                                                                                                                                                                                    students.Add(new Student(id, name, score));
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                    return students;
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                            public void WriteReportToFile(List<Student> students, string outputFilePath)
                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                        using var sw = new StreamWriter(outputFilePath);
                                                                                                                                                                                                                                                                                                                                                                                                                                foreach (var s in students)
                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    sw.WriteLine($"{s.FullName} (ID: {s.Id}): Score = {s.Score}, Grade = {s.GetGrade()}");
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                public class Program
                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public static void Main()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var processor = new StudentResultProcessor();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                string input = "sample_input.txt";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            string output = "report.txt";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var students = processor.ReadStudentsFromFile(input);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    processor.WriteReportToFile(students, output);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Console.WriteLine($"Processed {students.Count} students. Report written to {output}.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                catch (FileNotFoundException ex)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Console.WriteLine($"File not found: {ex.Message}");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    catch (InvalidScoreFormatException ex)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Console.WriteLine($"Invalid score: {ex.Message}");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        catch (MissingFieldException ex)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Console.WriteLine($"Missing field: {ex.Message}");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            catch (Exception ex)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Console.WriteLine($"Unexpected error: {ex.Message}");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }