using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;

// b) Marker interface
public interface IInventoryEntity
{
    int Id { get; }
    }

    // a) Immutable record implementing marker interface
    public record InventoryItem(int Id, string Name, int Quantity, DateTime DateAdded) : IInventoryEntity;

    // c) Generic Inventory Logger
    public class InventoryLogger<T> where T : IInventoryEntity
    {
        private readonly List<T> _log = new();
            private readonly string _filePath;

                public InventoryLogger(string filePath)
                    {
                            _filePath = filePath;
                                }

                                    public void Add(T item) => _log.Add(item);

                                        public List<T> GetAll() => new(_log);

                                            public void SaveToFile()
                                                {
                                                        try
                                                                {
                                                                            var options = new JsonSerializerOptions { WriteIndented = true };
                                                                                        using var fs = new FileStream(_filePath, FileMode.Create, FileAccess.Write, FileShare.None);
                                                                                                    JsonSerializer.Serialize(fs, _log, options);
                                                                                                            }
                                                                                                                    catch (Exception ex)
                                                                                                                            {
                                                                                                                                        Console.WriteLine($"Error saving to file: {ex.Message}");
                                                                                                                                                }
                                                                                                                                                    }

                                                                                                                                                        public void LoadFromFile()
                                                                                                                                                            {
                                                                                                                                                                    try
                                                                                                                                                                            {
                                                                                                                                                                                        if (!File.Exists(_filePath))
                                                                                                                                                                                                    {
                                                                                                                                                                                                                    Console.WriteLine("No saved data found.");
                                                                                                                                                                                                                                    return;
                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                            using var fs = new FileStream(_filePath, FileMode.Open, FileAccess.Read, FileShare.Read);
                                                                                                                                                                                                                                                                        var loaded = JsonSerializer.Deserialize<List<T>>(fs) ?? new List<T>();
                                                                                                                                                                                                                                                                                    _log.Clear();
                                                                                                                                                                                                                                                                                                _log.AddRange(loaded);
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                catch (Exception ex)
                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                    Console.WriteLine($"Error loading from file: {ex.Message}");
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                // f) InventoryApp
                                                                                                                                                                                                                                                                                                                                                public class InventoryApp
                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                    private readonly InventoryLogger<InventoryItem> _logger;

                                                                                                                                                                                                                                                                                                                                                        public InventoryApp(string filePath)
                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                    _logger = new InventoryLogger<InventoryItem>(filePath);
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                            public void SeedSampleData()
                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                        _logger.Add(new InventoryItem(1, "Pencils", 100, DateTime.Now));
                                                                                                                                                                                                                                                                                                                                                                                                _logger.Add(new InventoryItem(2, "Notebooks", 50, DateTime.Now));
                                                                                                                                                                                                                                                                                                                                                                                                        _logger.Add(new InventoryItem(3, "Markers", 30, DateTime.Now));
                                                                                                                                                                                                                                                                                                                                                                                                                _logger.Add(new InventoryItem(4, "Folders", 20, DateTime.Now));
                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                        public void SaveData() => _logger.SaveToFile();

                                                                                                                                                                                                                                                                                                                                                                                                                            public void LoadData() => _logger.LoadFromFile();

                                                                                                                                                                                                                                                                                                                                                                                                                                public void PrintAllItems()
                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                            Console.WriteLine("== Inventory Items ==");
                                                                                                                                                                                                                                                                                                                                                                                                                                                    foreach (var item in _logger.GetAll())
                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Console.WriteLine($"#{item.Id} {item.Name} x{item.Quantity} (Added: {item.DateAdded})");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public static void Main()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    string dataFile = "inventory.json";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // First session
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var app = new InventoryApp(dataFile);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.SeedSampleData();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.SaveData();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Simulate a new session
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    var newApp = new InventoryApp(dataFile);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            newApp.LoadData();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    newApp.PrintAllItems();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }