using System;
using System.Collections.Generic;
using System.Linq;

// a) Marker interface
public interface IInventoryItem
{
    int Id { get; }
        string Name { get; }
            int Quantity { get; set; }
            }

            // b) ElectronicItem
            public class ElectronicItem : IInventoryItem
            {
                public int Id { get; }
                    public string Name { get; }
                        public int Quantity { get; set; }
                            public string Brand { get; }
                                public int WarrantyMonths { get; }

                                    public ElectronicItem(int id, string name, int quantity, string brand, int warrantyMonths)
                                        {
                                                Id = id; Name = name; Quantity = quantity; Brand = brand; WarrantyMonths = warrantyMonths;
                                                    }

                                                        public override string ToString() => $"[Electronic] #{Id} {Name} ({Brand}) x{Quantity}, Warranty: {WarrantyMonths} mo";
                                                        }

                                                        // c) GroceryItem
                                                        public class GroceryItem : IInventoryItem
                                                        {
                                                            public int Id { get; }
                                                                public string Name { get; }
                                                                    public int Quantity { get; set; }
                                                                        public DateTime ExpiryDate { get; }

                                                                            public GroceryItem(int id, string name, int quantity, DateTime expiryDate)
                                                                                {
                                                                                        Id = id; Name = name; Quantity = quantity; ExpiryDate = expiryDate;
                                                                                            }

                                                                                                public override string ToString() => $"[Grocery] #{Id} {Name} x{Quantity}, Expires: {ExpiryDate:d}";
                                                                                                }

                                                                                                // e) Custom exceptions
                                                                                                public class DuplicateItemException : Exception
                                                                                                {
                                                                                                    public DuplicateItemException(string message) : base(message) { }
                                                                                                    }

                                                                                                    public class ItemNotFoundException : Exception
                                                                                                    {
                                                                                                        public ItemNotFoundException(string message) : base(message) { }
                                                                                                        }

                                                                                                        public class InvalidQuantityException : Exception
                                                                                                        {
                                                                                                            public InvalidQuantityException(string message) : base(message) { }
                                                                                                            }

                                                                                                            // d) Generic Inventory Repository
                                                                                                            public class InventoryRepository<T> where T : IInventoryItem
                                                                                                            {
                                                                                                                private readonly Dictionary<int, T> _items = new();

                                                                                                                    public void AddItem(T item)
                                                                                                                        {
                                                                                                                                if (_items.ContainsKey(item.Id))
                                                                                                                                            throw new DuplicateItemException($"Item with ID {item.Id} already exists.");
                                                                                                                                                    _items[item.Id] = item;
                                                                                                                                                        }

                                                                                                                                                            public T GetItemById(int id)
                                                                                                                                                                {
                                                                                                                                                                        if (!_items.TryGetValue(id, out var item))
                                                                                                                                                                                    throw new ItemNotFoundException($"Item with ID {id} not found.");
                                                                                                                                                                                            return item;
                                                                                                                                                                                                }

                                                                                                                                                                                                    public void RemoveItem(int id)
                                                                                                                                                                                                        {
                                                                                                                                                                                                                if (!_items.Remove(id))
                                                                                                                                                                                                                            throw new ItemNotFoundException($"Item with ID {id} not found for removal.");
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                    public List<T> GetAllItems() => _items.Values.ToList();

                                                                                                                                                                                                                                        public void UpdateQuantity(int id, int newQuantity)
                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                    if (newQuantity < 0)
                                                                                                                                                                                                                                                                throw new InvalidQuantityException("Quantity cannot be negative.");
                                                                                                                                                                                                                                                                        var item = GetItemById(id); // may throw ItemNotFoundException
                                                                                                                                                                                                                                                                                item.Quantity = newQuantity;
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                    // f) WareHouseManager
                                                                                                                                                                                                                                                                                    public class WareHouseManager
                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                        private readonly InventoryRepository<ElectronicItem> _electronics = new();
                                                                                                                                                                                                                                                                                            private readonly InventoryRepository<GroceryItem> _groceries = new();

                                                                                                                                                                                                                                                                                                public void SeedData()
                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                            _electronics.AddItem(new ElectronicItem(1, "Laptop", 10, "Dell", 24));
                                                                                                                                                                                                                                                                                                                    _electronics.AddItem(new ElectronicItem(2, "Smartphone", 25, "Samsung", 12));
                                                                                                                                                                                                                                                                                                                            _electronics.AddItem(new ElectronicItem(3, "Headphones", 15, "Sony", 18));

                                                                                                                                                                                                                                                                                                                                    _groceries.AddItem(new GroceryItem(1, "Milk", 50, DateTime.Today.AddDays(7)));
                                                                                                                                                                                                                                                                                                                                            _groceries.AddItem(new GroceryItem(2, "Bread", 30, DateTime.Today.AddDays(3)));
                                                                                                                                                                                                                                                                                                                                                    _groceries.AddItem(new GroceryItem(3, "Eggs", 60, DateTime.Today.AddDays(10)));
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                            public void PrintAllItems<T>(InventoryRepository<T> repo) where T : IInventoryItem
                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                        foreach (var item in repo.GetAllItems())
                                                                                                                                                                                                                                                                                                                                                                                    Console.WriteLine(item);
                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                            public void IncreaseStock<T>(InventoryRepository<T> repo, int id, int quantity) where T : IInventoryItem
                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                        try
                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                            var item = repo.GetItemById(id);
                                                                                                                                                                                                                                                                                                                                                                                                                                        repo.UpdateQuantity(id, item.Quantity + quantity);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    Console.WriteLine($"Stock increased: #{id} now {item.Quantity}");
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    catch (Exception ex) when (ex is ItemNotFoundException or InvalidQuantityException)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Console.WriteLine($"Error increasing stock: {ex.Message}");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public void RemoveItemById<T>(InventoryRepository<T> repo, int id) where T : IInventoryItem
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        repo.RemoveItem(id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Console.WriteLine($"Removed item #{id}");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    catch (ItemNotFoundException ex)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Console.WriteLine($"Error removing item: {ex.Message}");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public void Run()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    SeedData();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Console.WriteLine("== Grocery Items ==");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    PrintAllItems(_groceries);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Console.WriteLine("\n== Electronic Items ==");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    PrintAllItems(_electronics);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Console.WriteLine("\n== Exception Scenarios ==");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Add a duplicate item
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _electronics.AddItem(new ElectronicItem(1, "Tablet", 5, "Apple", 12));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                catch (DuplicateItemException ex)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Console.WriteLine($"Duplicate add caught: {ex.Message}");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Remove a non-existent item
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            RemoveItemById(_groceries, 999);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Update with invalid quantity
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _electronics.UpdateQuantity(2, -10);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                catch (InvalidQuantityException ex)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Console.WriteLine($"Invalid quantity caught: {ex.Message}");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public class Program
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public static void Main()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                new WareHouseManager().Run();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }